# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 01:00
from __future__ import unicode_literals

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('state_province', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=2)),
            ],
            bases=(common.models.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
