# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 22:18
from __future__ import unicode_literals

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20180116_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='attention',
            field=common.models.OptionalCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=common.models.RequiredCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=common.models.RequiredCharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=common.models.OptionalCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='state_province',
            field=common.models.OptionalCharField(max_length=200),
        ),
    ]
