# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_auto_20180123_2218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('attention', 'address', 'city', 'state_province', 'postal_code', 'country')]),
        ),
    ]
