# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20180123_2229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('address', 'city', 'country', 'attention', 'state_province', 'postal_code')]),
        ),
    ]
