# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 19:46
from __future__ import unicode_literals

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0007_create_initial_address_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=common.models.OptionalTextField(),
        ),
    ]
