# Generated by Django 3.1.2 on 2020-11-24 18:57

import common.models
import django.core.validators
from django.db import migrations
import re


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0008_auto_20181025_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='id',
            field=common.models.RequiredCharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
