# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresstype',
            name='type',
        ),
        migrations.AlterField(
            model_name='addresstype',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set([('address', 'city')]),
        ),
    ]
