# Generated by Django 3.1.2 on 2020-10-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_create_post_gis_extension'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['domain'], 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
