# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 23:01
from __future__ import unicode_literals

import common.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabulary', common.models.RequiredCharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('name', common.models.RequiredCharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z', 32), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
            ],
            options={
                'verbose_name': 'vocabulary',
                'verbose_name_plural': 'taxonomies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='taxonomy',
            unique_together=set([('vocabulary', 'name')]),
        ),
    ]
