# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 23:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0002_auto_20171220_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonomyterm',
            old_name='vocabulary',
            new_name='taxonomy_id',
        ),
        migrations.AlterUniqueTogether(
            name='taxonomyterm',
            unique_together=set([('taxonomy_id', 'name')]),
        ),
    ]
