# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-07 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_at_location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneatlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='locations.Location'),
        ),
    ]
