# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_at_location', '0002_auto_20180906_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneatlocation',
            name='phone_number',
            field=models.TextField(),
        ),
    ]
