# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 01:03
from __future__ import unicode_literals

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('locations', '0004_auto_20171221_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressAtLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.Address')),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.AddressType')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            bases=(common.models.ValidateOnSaveMixin, models.Model),
        ),
        migrations.AddField(
            model_name='location',
            name='addresses',
            field=models.ManyToManyField(related_name='locations', through='locations.AddressAtLocation', to='addresses.Address'),
        ),
    ]
