# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20180116_0103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressAtLocation',
            new_name='LocationAddress',
        ),
    ]
