# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20180208_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceatlocation',
            options={'ordering': ['id']},
        ),
    ]
