# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-10 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20180227_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.Organization'),
        ),
        migrations.AlterField(
            model_name='locationaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.Address'),
        ),
        migrations.AlterField(
            model_name='locationaddress',
            name='address_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.AddressType'),
        ),
        migrations.AlterField(
            model_name='locationaddress',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_addresses', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='serviceatlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='serviceatlocation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Service'),
        ),
    ]
