# Generated by Django 2.1.2 on 2019-01-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20180910_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='addresses',
        ),
    ]
