# Generated by Django 2.2.4 on 2019-12-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_remove_location_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationaddress',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_addresses', to='locations.Location'),
        ),
    ]
