# Generated by Django 3.0.7 on 2020-07-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20191230_2324'),
        ('locations', '0014_auto_20200409_1740'),
    ]

    operations = [
    ]
