# Generated by Django 3.0.2 on 2020-02-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200206_2254'),
        ('locations', '0015_auto_20200206_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceatlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='serviceatlocation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
    ]
