# Generated by Django 3.0.7 on 2020-07-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_auto_20200207_2110'),
        ('locations', '0015_merge_20200706_1813'),
    ]

    operations = [
    ]
