# Generated by Django 3.1.2 on 2020-10-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0017_merge_20200706_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtranslation',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
