# Generated by Django 3.1.2 on 2020-12-10 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_locationtranslation_alternate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationtranslation',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
