# Generated by Django 3.1.2 on 2020-12-12 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0019_auto_20201210_0120'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationaddress',
            unique_together=set(),
        ),
    ]
