# Generated by Django 3.1.2 on 2020-12-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0010_auto_20201126_2148'),
        ('locations', '0020_auto_20201212_0020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationaddress',
            unique_together={('location', 'address_type')},
        ),
    ]
