# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0003_auto_20171220_2335'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='taxonomyTerms',
            field=models.ManyToManyField(db_table='services_service_taxonomy_terms', to='taxonomies.TaxonomyTerm'),
        ),
    ]
