# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 21:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_taxonomyterms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='taxonomyTerms',
            new_name='taxonomy_terms',
        ),
    ]
