# Generated by Django 2.2.2 on 2019-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField()),
            ],
        ),
    ]
