# Generated by Django 2.2.2 on 2019-10-02 18:25

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=common.models.RequiredCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='notes',
            field=common.models.OptionalTextField(),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='url',
            field=common.models.RequiredURLField(),
        ),
    ]
