# Generated by Django 2.2.2 on 2019-10-02 22:05

import common.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa_tool', '0002_auto_20191002_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', common.models.OptionalTextField()),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
