# Generated by Django 3.0.7 on 2020-07-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa_tool', '0002_auto_20200409_1740'),
        ('qa_tool', '0002_auto_20191230_2252'),
    ]

    operations = [
    ]
