# Generated by Django 2.2.2 on 2019-10-03 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0005_auto_20180910_1743'),
        ('qa_tool', '0003_searchlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('time_stamp', models.DateTimeField()),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qa_tool.Algorithm')),
                ('search_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qa_tool.SearchLocation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
