# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxonomy',
            new_name='TaxonomyTerm',
        ),
        migrations.AlterModelOptions(
            name='taxonomyterm',
            options={'verbose_name': 'taxonomy term', 'verbose_name_plural': 'taxonomy terms'},
        ),
    ]
