# Generated by Django 3.0.4 on 2020-04-09 17:40

import common.models
import django.core.validators
from django.db import migrations
import re


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0003_auto_20171220_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomyterm',
            name='name',
            field=common.models.RequiredCharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='taxonomyterm',
            name='taxonomy_id',
            field=common.models.RequiredCharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
