# Generated by Django 3.0.7 on 2020-07-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0004_auto_20200206_2254'),
        ('taxonomies', '0004_auto_20200409_1740'),
    ]

    operations = [
    ]
