# Generated by Django 3.1.2 on 2020-12-30 22:08

import common.models
import django.core.validators
from django.db import migrations
import re


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0005_merge_20200706_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomyterm',
            name='taxonomy_term_id',
            field=common.models.RequiredCharField(default='8c85dfe8-238e-4a6c-9e1c-9f3d4aecaa1c', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
