# Generated by Django 3.1.2 on 2020-12-30 22:08

import common.models
import django.core.validators
from django.db import migrations
import re
import taxonomies.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0006_taxonomyterm_taxonomy_term_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomyterm',
            name='taxonomy_term_id',
            field=common.models.RequiredCharField(default=taxonomies.models.default_term_id, max_length=200, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')]),
        ),
    ]
