# Generated by Django 3.0.7 on 2020-07-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_auto_20200206_2254'),
        ('organizations', '0005_auto_20200409_1740'),
    ]

    operations = [
    ]
