# Generated by Django 3.1.2 on 2020-10-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_merge_20200706_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationtranslation',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
