# Generated by Django 3.1.2 on 2020-11-16 23:26

import common.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organizationtranslation_alternate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=common.models.OptionalCharField(max_length=255, validators=[django.core.validators.URLValidator()]),
        ),
    ]
