# Generated by Django 3.1.2 on 2020-12-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20201116_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationtranslation',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
