# Generated by Django 2.2.4 on 2019-11-12 21:20

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotificationtoken',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='pushnotificationtoken',
            name='locale',
            field=common.models.RequiredCharField(default='en', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='id',
            field=common.models.RequiredCharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
