# Generated by Django 2.2.4 on 2019-11-14 00:24

import common.models
from django.db import migrations, models
import push_notifications.validation


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0002_auto_20191112_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationtoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='id',
            field=common.models.RequiredCharField(max_length=200, primary_key=True, serialize=False, validators=[push_notifications.validation.validate_token]),
        ),
    ]
