# Generated by Django 3.0.4 on 2020-04-21 17:59

import common.models
from django.db import migrations
import push_notifications.validation


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0003_auto_20191114_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotificationtoken',
            name='api_key',
            field=common.models.RequiredCharField(default='omitted', max_length=50, validators=[push_notifications.validation.validate_api_key]),
        ),
    ]
