# Generated by Django 3.0.4 on 2020-04-21 20:24

import common.models
import django.core.validators
from django.db import migrations
import push_notifications.validation


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0004_pushnotificationtoken_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='api_key',
            field=common.models.RequiredCharField(default='omitted', max_length=50, validators=[push_notifications.validation.validate_api_key, django.core.validators.RegexValidator(regex='.+')]),
        ),
    ]
