# Generated by Django 3.0.4 on 2020-04-21 20:50

import common.models
from django.db import migrations
import push_notifications.validation


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0005_auto_20200421_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotificationtoken',
            name='api_key',
            field=common.models.RequiredCharField(max_length=50, validators=[push_notifications.validation.validate_api_key]),
        ),
    ]
