# Generated by Django 3.1.2 on 2020-10-26 23:19

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0006_auto_20200421_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwaysApiKey',
            fields=[
                ('id', common.models.RequiredCharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
