# Generated by Django 3.0.4 on 2020-04-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20200409_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='last_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
