# Generated by Django 3.0.7 on 2020-07-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_last_verified_date'),
        ('services', '0006_auto_20200206_2254'),
    ]

    operations = [
    ]
