# Generated by Django 3.1.2 on 2020-10-27 21:25

import common.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicetranslation_alternate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='email',
            field=common.models.OptionalCharField(max_length=200, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='service',
            name='website',
            field=common.models.OptionalCharField(max_length=200, validators=[django.core.validators.URLValidator()]),
        ),
    ]
