# Generated by Django 3.1.2 on 2020-12-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20201123_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetranslation',
            name='alternate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
