# Generated by Django 2.1.2 on 2018-11-05 16:03

import common.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSimilarityScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_task_id', common.models.RequiredCharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('second_task_id', common.models.RequiredCharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('similarity_score', models.FloatField()),
            ],
            bases=(common.models.ValidateOnSaveMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tasksimilarityscores',
            unique_together={('first_task_id', 'second_task_id')},
        ),
    ]
