# Generated by Django 2.1.2 on 2018-11-06 20:53

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180910_1743'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskServiceSimilarityScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', common.models.RequiredCharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('similarity_score', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.Service')),
            ],
            bases=(common.models.ValidateOnSaveMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='taskservicesimilarityscores',
            unique_together={('task_id', 'service')},
        ),
    ]
