# Generated by Django 2.1.2 on 2018-11-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20181106_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskservicesimilarityscores',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Service'),
        ),
    ]
