# Generated by Django 2.1.2 on 2018-11-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20181109_0009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskSimilarityScores',
            new_name='TaskSimilarityScore',
        ),
    ]
