# Generated by Django 2.1.2 on 2018-12-04 17:46

import common.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import parler.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0005_auto_20180910_1743'),
        ('search', '0006_auto_20181204_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', common.models.RequiredCharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
            ],
            options={
                'abstract': False,
            },
            bases=(common.models.ValidateOnSaveMixin, parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskServiceSimilarityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.Service')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Task')),
            ],
            bases=(common.models.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskSimilarityScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('first_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_task', to='search.Task')),
                ('second_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_task', to='search.Task')),
            ],
            bases=(common.models.ValidateOnSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TaskTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='search.Task')),
            ],
            options={
                'verbose_name': 'task Translation',
                'db_table': 'search_task_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='tasktranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='tasksimilarityscore',
            unique_together={('first_task', 'second_task')},
        ),
        migrations.AlterUniqueTogether(
            name='taskservicesimilarityscore',
            unique_together={('task', 'service')},
        ),
    ]
