# Generated by Django 2.1.2 on 2019-01-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomies', '0003_auto_20171220_2335'),
        ('search', '0007_auto_20181204_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taxonomy_terms',
            field=models.ManyToManyField(db_table='topic_taxonomy_terms', to='taxonomies.TaxonomyTerm'),
        ),
    ]
