# Generated by Django 2.2.1 on 2019-07-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_task_taxonomy_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktranslation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
