# Generated by Django 2.2.4 on 2019-12-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20190725_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
    ]
