# Generated by Django 3.0.7 on 2020-07-06 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20191230_2252'),
        ('search', '0010_auto_20200409_1740'),
    ]

    operations = [
    ]
