# Generated by Django 3.0.7 on 2020-07-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20200206_2254'),
        ('search', '0011_merge_20200706_1811'),
    ]

    operations = [
    ]
