# Generated by Django 3.0.4 on 2020-05-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='alerttranslation',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='alerttranslation',
            old_name='title',
            new_name='heading',
        ),
    ]
