# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_servicelocation_servicelocationtranslation'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelocation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
        migrations.AddField(
            model_name='location',
            name='services',
            field=models.ManyToManyField(related_name='locations', through='locations.ServiceLocation', to='services.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='servicelocationtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
