# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20180126_2109'),
        ('locations', '0006_auto_20180123_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationaddress',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_locations', to='addresses.Address'),
        ),
        migrations.AlterField(
            model_name='locationaddress',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_addresses', to='locations.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='locationaddress',
            unique_together=set([('location', 'address_type')]),
        ),
    ]
